// Auth constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const RESET_LOGIN_STATE = 'RESET_LOGIN_STATE';

// Fetch Restaurant list
export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILURE = 'FETCH_LIST_FAILURE';
export const RESET_LIST_STATE = 'RESET_LIST_STATE';

//Fetch Fetch Dine In resturants
export const FETCH_COLLECTING_LIST_REQUEST = 'FETCH_COLLECTING_LIST_REQUEST';
export const FETCH_COLLECTING_LIST_SUCCESS = 'FETCH_COLLECTING_LIST_SUCCESS';
export const FETCH_COLLECTING_LIST_FAILURE = 'FETCH_COLLECTING_LIST_FAILURE';


// Fetch Restaurant list
export const FETCH_DETAIL_REQUEST = 'FETCH_DETAIL_REQUEST';
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';
export const FETCH_DETAIL_FAILURE = 'FETCH_DETAIL_FAILURE';
export const RESET_DETAIL_STATE = 'RESET_DETAIL_STATE';

// Fetch Orders list
export const FETCH_USER_ORDERS_REQUEST = 'FETCH_USER_ORDERS_REQUEST';
export const FETCH_USER_ORDERS_SUCCESS = 'FETCH_USER_ORDERS_SUCCESS';
export const FETCH_USER_ORDERS_FAILURE = 'FETCH_USER_ORDERS_FAILURE';
export const RESET_ORDERS_STATE = 'RESET_ORDERS_STATE';
export const ADD_ITEM_QUANTITY = 'ADD_ITEM_QUANTITY';
export const SUBTRACT_ITEM_QUANTITY = 'SUBTRACT_ITEM_QUANTITY';

//Fetch Complete Orders
export const FETCH_COMPLETED_ORDERS = 'FETCH_COMPLETED_ORDERS'

// Fetch
export const FETCH_RESTAURENTS_REQUEST = 'FETCH_RESTAURENTS_REQUEST';
export const FETCH_RESTAURENTS_SUCCESS = 'FETCH_RESTAURENTS_SUCCESS';
export const FETCH_RESTAURENTS_FAILURE = 'FETCH_RESTAURENTS_FAILURE';
export const RESET_RESTAURENTS_STATE = 'RESET_RESTAURENTS_STATE';

// User Profile constants
export const PROFILE_DATEILS_REQUEST = 'PROFILE_DATEILS_REQUEST';
export const PROFILE_DATEILS_SUCCESS = 'PROFILE_DATEILS_SUCCESS';
export const PROFILE_DATEILS_FAILURE = 'PROFILE_DATEILS_FAILURE';
export const RESET_USER_PROFILE = 'RESET_USER_PROFILE';

//Add Item to Card Action
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';

//place Order Constants
export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE';
export const RESET_PLACE_ORDER_STATE = 'RESET_PLACE_ORDER_STATE';


//Set collecting resturant Action 
export const SET_COLLECTING_RESTAURANT = 'SET_COLLECTING_RESTAURANT';
export const SET_DELIVERY_RESTAURANT = 'SET_DELIVERY_RESTAURANT';

/*
*****************************************************************
                    Restutant Owner, Actions
                    Will Be listed down here
*****************************************************************
*/

// Stripe Dashboard Fetch Constants
export const FETCH_DASHBORAD_URL_REQUEST = 'FETCH_DASHBORAD_URL_REQUEST';
export const FETCH_DASHBORAD_URL_SUCCESS = 'FETCH_DASHBORAD_URL_SUCCESS';
export const FETCH_DASHBORAD_URL_FAILURE = 'FETCH_DASHBORAD_URL_FAILURE';

// Restaurant PaymentHistory Constants
export const FETCH_PAYMENT_HISTORY_REQUEST = 'FETCH_PAYMENT_HISTORY_REQUEST';
export const FETCH_PAYMENT_HISTORY_SUCCESS = 'FETCH_PAYMENT_HISTORY_SUCCESS';
export const FETCH_PAYMENT_HISTORY_FAILURE = 'FETCH_PAYMENT_HISTORY_FAILURE';

// Restaurant Profile Constants
export const UPDATE_RESATURANT_PROFILE_REQUEST = 'UPDATE_RESTAURANT_PROFILE_REQUEST';
export const UPDATE_RESATURANT_PROFILE_SUCCESS = 'UPDATE_RESATURANT_PROFILE_SUCCESS';
export const UPDATE_RESATURANT_PROFILE_FAILURE = 'UPDATE_RESATURANT_PROFILE_FAILURE';

export const CHECK_RESTAURANT_EXIST_REQUEST = 'CHECK_RESTAURANT_EXIST_REQUEST';
export const CHECK_RESTAURANT_EXIST_SUCCESS = 'CHECK_RESTAURANT_EXIST_SUCCESS';
export const CHECK_RESTAURANT_EXIST_FAILURE = 'CHECK_RESTAURANT_EXIST_FAILURE';
export const RESET_RESATURANT_PROFILE_STATE = 'RESET_RESATURANT_PROFILE_STATE';

// Fetch Category list
export const FETCH_CATEGORY_LIST_REQUEST = 'FETCH_CATEGORY_LIST_REQUEST';
export const FETCH_CATEGORY_LIST_SUCCESS = 'FETCH_CATEGORY_LIST_SUCCESS';
export const FETCH_CATEGORY_LIST_FAILURE = 'FETCH_CATEGORY_LIST_FAILURE';
export const RESET_CATEGORY_LIST_STATE = 'RESET_CATEGORY_LIST_STATE';

// Add Category Constants
export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const ADD_CATEGORY_LOCALLY = 'ADD_CATEGORY_LOCALLY';
export const RESET_CATEGORY_STATE = 'RESET_CATEGORY_STATE';

// Delete Category Constants
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

// Add Category Item Constants
export const ADD_CATEGORY_ITEM_REQUEST = 'ADD_CATEGORY_ITEM_REQUEST';
export const ADD_CATEGORY_ITEM_SUCCESS = 'ADD_CATEGORY_ITEM_SUCCESS';
export const ADD_CATEGORY_ITEM_FAILURE = 'ADD_CATEGORY_ITEM_FAILURE';
export const ADD_CATEGORY_ITEM_LOCALLY = 'ADD_CATEGORY_ITEM_LOCALLY';
export const RESET_CATEGORY_ITEM_STATE = 'RESET_CATEGORY_ITEM_STATE';

// Remove Category Item Constants
export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_LOCALLY = 'REMOVE_ITEM_LOCALLY';
export const REMOVE_ITEM_FAILURE = 'REMOVE_ITEM_FAILURE';

//Toggle Action UI
export const TOGGLE_ACTION = 'TOGGLE_ACTION';
export const SELECT_ALL_CATEGORY = 'SELECT_ALL_CATEGORY';

// Fetch Restaurant Orders list
export const FETCH_RESTAURANT_ORDERS_REQUEST = 'FETCH_RESTAURANT_ORDERS_REQUEST';
export const FETCH_RESTAURANT_DELIVERIES_ORDERS_SUCCESS = 'FETCH_RESTAURANT_DELIVERIES_ORDERS_SUCCESS';
export const FETCH_RESTAURANT_COLLECTION_ORDERS_SUCCESS = 'FETCH_RESTAURANT_COLLECTION_ORDERS_SUCCESS';

export const FETCH_RESTAURANT_ORDERS_FAILURE = 'FETCH_RESTAURANT_ORDERS_FAILURE';
export const RESET_RESTAURANT_ORDERS_STATE = 'RESET_RESTAURANT_ORDERS_STATE';
export const RESET_COMPLETED_ORDERS = 'RESET_COMPLETED_ORDERS'
export const RESET_MY_ORDERS = 'RESET_MY_ORDERS'
export const RESET_DINEIN_ORDERS = 'RESET_DINEIN_ORDERS'




// Update Restaurant Orders list
export const UPDATE_RESTAURANT_ORDERS_REQUEST = 'UPDATE_RESTAURANT_ORDERS_REQUEST';
export const UPDATE_RESTAURANT_ORDERS_SUCCESS = 'UPDATE_RESTAURANT_ORDERS_SUCCESS';
export const UPDATE_RESTAURANT_ORDERS_FAILURE = 'UPDATE_RESTAURANT_ORDERS_FAILURE';
export const UPDATE_STATUS_LOCALLY = 'UPDATE_STATUS_LOCALLY';
